# Generated by Django 3.2.7 on 2021-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.PositiveBigIntegerField(default='0000000000'),
        ),
    ]
