# Generated by Django 3.2.7 on 2021-11-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
