# Generated by Django 3.2.7 on 2021-10-29 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_dimension_LxWxH', models.CharField(blank=True, max_length=200, null=True)),
                ('date_first_available', models.DateField(auto_now_add=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('packer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('net_quantity', models.IntegerField(blank=True, null=True)),
                ('included_components', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='types/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('size', models.CharField(choices=[('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('detail', models.TextField()),
                ('stock', models.PositiveBigIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0)),
                ('comment', models.ManyToManyField(blank=True, to='product.Comment')),
                ('specification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification_of_product', to='product.specification')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_product', to='product.type')),
            ],
            options={
                'ordering': ['edited'],
            },
        ),
    ]
