# Generated by Django 3.2.7 on 2021-10-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_dimension_LxWxH', models.CharField(blank=True, max_length=200, null=True)),
                ('date_first_available', models.DateField(auto_now_add=True, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('packer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('item_weight', models.FloatField(blank=True, null=True)),
                ('net_quantity', models.IntegerField(blank=True, null=True)),
                ('included_components', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification_of_product', to='product.specification'),
        ),
    ]
