# Generated by Django 3.2.7 on 2021-10-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='textEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
