# Generated by Django 3.2.7 on 2021-11-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offer_product'),
        ('product', '0003_alter_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_of_product', to='offer.offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors_available',
            field=models.ManyToManyField(blank=True, related_name='colors_available_of_product', to='product.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes_available',
            field=models.ManyToManyField(blank=True, related_name='size_available_of_product', to='product.Size'),
        ),
    ]
