# Generated by Django 3.2.7 on 2021-12-07 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Will Be Automatically Calculated', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
