# Generated by Django 3.2.7 on 2021-11-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211114_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specification_of_product', to='product.specification'),
        ),
    ]
