# Generated by Django 3.2.7 on 2021-10-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211006_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='textEditor',
        ),
    ]
