# Generated by Django 3.2.7 on 2021-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors_available',
            field=models.ManyToManyField(related_name='colors_available_of_product', to='product.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes_available',
            field=models.ManyToManyField(related_name='size_available_of_product', to='product.Size'),
        ),
    ]
