# Generated by Django 3.2.7 on 2021-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_remove_review_product'),
        ('product', '0006_auto_20211114_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, null=True, related_name='review_of_product', to='review.Review'),
        ),
    ]
