# Generated by Django 3.2.6 on 2021-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
