# Generated by Django 3.2.6 on 2021-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0002_shirt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
