# Generated by Django 3.2.6 on 2021-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0003_shirt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='shirt_type',
            field=models.CharField(default='HALF', max_length=4),
        ),
    ]
