# Generated by Django 3.2.6 on 2021-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0004_shirt_shirt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_type',
            field=models.CharField(choices=[('HALF', 'HALF'), ('FULL', 'FULL')], default='HALF', max_length=4),
        ),
    ]
