# Generated by Django 3.2.6 on 2021-08-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0005_alter_shirt_shirt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
