# Generated by Django 3.2.7 on 2021-10-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('offer', '0002_offer_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
