# Generated by Django 3.2.6 on 2021-08-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('short_type', models.CharField(choices=[('RUNNING', 'RUNNING'), ('CARGO', 'CARGO'), ('PLEATED', 'PLEATED'), ('FLAT FRONT', 'FLAT FRONT'), ('DENIM', 'DENIM'), ('SWIMMING TRUNKS', 'SWIMMING TRUNKS'), ('BERMUDA', 'BERMUDA')], default='BERMUDA', max_length=15)),
                ('short_size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
