# Generated by Django 3.2.7 on 2021-11-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20211107_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='image_of_review', to='review.ReviewImage'),
        ),
    ]
