# Generated by Django 3.2.7 on 2021-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20211107_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_of_review', to='review.ReviewImage'),
        ),
    ]
