# Generated by Django 3.2.7 on 2021-11-16 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0007_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_of_reviewimage', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_reviewimage', to='auth.user'),
            preserve_default=False,
        ),
    ]
