# Generated by Django 3.2.7 on 2021-11-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20211116_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reviewimage',
            name='user',
        ),
    ]
