# Generated by Django 3.2.7 on 2021-11-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20211116_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='user_review_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
