# Generated by Django 3.2.7 on 2021-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20211118_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
    ]
