# Generated by Django 3.2.7 on 2021-11-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0016_remove_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_of_reviewimage', to='auth.user'),
            preserve_default=False,
        ),
    ]
