# Generated by Django 3.2.7 on 2021-11-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_reviewimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='user',
        ),
    ]
