# Generated by Django 3.2.7 on 2021-12-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i1', models.ImageField(blank=True, default='carousel_default/1.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
                ('i2', models.ImageField(blank=True, default='carousel_default/2.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
                ('i3', models.ImageField(blank=True, default='carousel_default/3.jpg', unique=True, upload_to='carousel/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
