# Generated by Django 3.2.7 on 2021-12-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_of_gallery', to='product.product'),
        ),
    ]
