# Generated by Django 3.2.7 on 2021-11-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Featured',
        ),
    ]
