# Generated by Django 3.2.7 on 2021-10-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselImages',
            new_name='CarouselImage',
        ),
    ]
