# Generated by Django 3.2.7 on 2021-10-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_texteditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='textEditor',
        ),
    ]
