# Generated by Django 3.2.7 on 2021-12-01 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('size', models.CharField(blank=True, max_length=1000)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
