# Generated by Django 3.2.6 on 2021-09-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
