# Generated by Django 3.2.7 on 2021-09-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock',
        ),
    ]
