# Generated by Django 3.2.7 on 2021-12-01 08:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_order_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('zip', models.PositiveBigIntegerField()),
                ('phonenumber', models.PositiveBigIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('dispatched', models.BooleanField()),
                ('dispatched_timestamp', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField()),
                ('delivered_timestamp', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
