# Generated by Django 3.2.7 on 2021-11-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.total'),
        ),
    ]
